# Generated by Django 6.0 on 2025-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_subject_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
