# Generated by Django 6.0 on 2025-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
