# Generated by Django 5.2.16 on 2026-07-17 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_enrollment_id_alter_subject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('University Core', 'University Core'), ('College Core', 'College Core'), ('Math/Science', 'Math/Science'), ('CPE Core', 'CPE Core'), ('Technical Elective', 'Technical Elective'), ('General Elective', 'General Elective')], default='CPE Core', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='plan_semester',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='plan_year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('days_and_time', models.CharField(max_length=100)),
                ('days_pattern', models.CharField(default='MW', max_length=10)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('instructor', models.CharField(default='TBD', max_length=100)),
                ('room', models.CharField(default='TBD', max_length=50)),
                ('seats_total', models.PositiveIntegerField(default=35)),
                ('seats_available', models.PositiveIntegerField(default=35)),
                ('final_exam_date', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='portal.subject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='portal.section'),
        ),
        migrations.CreateModel(
            name='StudentCourseGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('points', models.FloatField()),
                ('term', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.subject')),
            ],
        ),
    ]
